version: '3'

env:
  CONFIG_PATH: ./config/local.yaml

tasks:
  build:
    cmds:
      - cd bin; go build ../cmd/main.go; cd ..
  run:
    deps: [build]
    cmds:
      - ./bin/main
  test:
    cmds:
      - go test