env: "local"
storage_host: "localhost"
storage_port: 5432
storage_user: "postgres"
storage_password: "root"
storage_database: "pfly"
http_server:
    address: "localhost:8082"
    timeout: 4s
    idle_timeout: 60s